In [73]:
import pandas as pd
# 设置pd显示时不换行
pd.set_option('display.width', 5000)
data = pd.read_csv("data/fish.csv")
data.head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Bream</td>
      <td>AF</td>
      <td>242.0</td>
      <td>23.2</td>
      <td>25.4</td>
      <td>30.0</td>
      <td>11.5200</td>
      <td>4.0200</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Bream</td>
      <td>NY</td>
      <td>290.0</td>
      <td>24.0</td>
      <td>26.3</td>
      <td>31.2</td>
      <td>12.4800</td>
      <td>4.3056</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Bream</td>
      <td>AS</td>
      <td>340.0</td>
      <td>23.9</td>
      <td>26.5</td>
      <td>31.1</td>
      <td>12.3778</td>
      <td>4.6961</td>
    </tr>
  </tbody>
</table>
</div>

## 1. 数据过滤
#### 1.1 单个条件过滤

In [74]:
filt = data["Length1"] > 25
data[filt].head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3</th>
      <td>Bream</td>
      <td>AS</td>
      <td>363.0</td>
      <td>26.3</td>
      <td>29.0</td>
      <td>33.5</td>
      <td>12.7300</td>
      <td>4.4555</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Bream</td>
      <td>AF</td>
      <td>430.0</td>
      <td>26.5</td>
      <td>29.0</td>
      <td>34.0</td>
      <td>12.4440</td>
      <td>5.1340</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Bream</td>
      <td>NY</td>
      <td>450.0</td>
      <td>26.8</td>
      <td>29.7</td>
      <td>34.7</td>
      <td>13.6024</td>
      <td>4.9274</td>
    </tr>
  </tbody>
</table>
</div>

In [75]:
filt = data["Species"] != "Bream"
data[filt].head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>35</th>
      <td>Roach</td>
      <td>AF</td>
      <td>40.0</td>
      <td>12.9</td>
      <td>14.1</td>
      <td>16.2</td>
      <td>4.1472</td>
      <td>2.2680</td>
    </tr>
    <tr>
      <th>36</th>
      <td>Roach</td>
      <td>AS</td>
      <td>69.0</td>
      <td>16.5</td>
      <td>18.2</td>
      <td>20.3</td>
      <td>5.2983</td>
      <td>2.8217</td>
    </tr>
    <tr>
      <th>37</th>
      <td>Roach</td>
      <td>SA</td>
      <td>78.0</td>
      <td>17.5</td>
      <td>18.8</td>
      <td>21.2</td>
      <td>5.5756</td>
      <td>2.9044</td>
    </tr>
  </tbody>
</table>
</div>

#### 1.2 多个条件过滤

In [76]:
filt1 = data["Species"] !="Bream"
filt2 = data["Width"] > 5
data[filt1 & filt2].head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>54</th>
      <td>Roach</td>
      <td>EN</td>
      <td>390.0</td>
      <td>29.5</td>
      <td>31.7</td>
      <td>35.0</td>
      <td>9.4850</td>
      <td>5.3550</td>
    </tr>
    <tr>
      <th>58</th>
      <td>Whitefish</td>
      <td>EN</td>
      <td>540.0</td>
      <td>28.5</td>
      <td>31.0</td>
      <td>34.0</td>
      <td>10.7440</td>
      <td>6.5620</td>
    </tr>
    <tr>
      <th>59</th>
      <td>Whitefish</td>
      <td>EN</td>
      <td>800.0</td>
      <td>33.7</td>
      <td>36.4</td>
      <td>39.6</td>
      <td>11.7612</td>
      <td>6.5736</td>
    </tr>
  </tbody>
</table>
</div>

In [77]:
data[filt1 | filt2].head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4</th>
      <td>Bream</td>
      <td>AF</td>
      <td>430.0</td>
      <td>26.5</td>
      <td>29.0</td>
      <td>34.0</td>
      <td>12.4440</td>
      <td>5.1340</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Bream</td>
      <td>SA</td>
      <td>500.0</td>
      <td>26.8</td>
      <td>29.7</td>
      <td>34.5</td>
      <td>14.1795</td>
      <td>5.2785</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Bream</td>
      <td>AN</td>
      <td>475.0</td>
      <td>28.4</td>
      <td>31.0</td>
      <td>36.2</td>
      <td>14.2628</td>
      <td>5.1042</td>
    </tr>
  </tbody>
</table>
</div>

#### 1.3 通过query方式过滤  
代码更可读

In [78]:
data.query("Length1>25").head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3</th>
      <td>Bream</td>
      <td>AS</td>
      <td>363.0</td>
      <td>26.3</td>
      <td>29.0</td>
      <td>33.5</td>
      <td>12.7300</td>
      <td>4.4555</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Bream</td>
      <td>AF</td>
      <td>430.0</td>
      <td>26.5</td>
      <td>29.0</td>
      <td>34.0</td>
      <td>12.4440</td>
      <td>5.1340</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Bream</td>
      <td>NY</td>
      <td>450.0</td>
      <td>26.8</td>
      <td>29.7</td>
      <td>34.7</td>
      <td>13.6024</td>
      <td>4.9274</td>
    </tr>
  </tbody>
</table>
</div>

In [79]:
data.query("Species!='Bream'").head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>35</th>
      <td>Roach</td>
      <td>AF</td>
      <td>40.0</td>
      <td>12.9</td>
      <td>14.1</td>
      <td>16.2</td>
      <td>4.1472</td>
      <td>2.2680</td>
    </tr>
    <tr>
      <th>36</th>
      <td>Roach</td>
      <td>AS</td>
      <td>69.0</td>
      <td>16.5</td>
      <td>18.2</td>
      <td>20.3</td>
      <td>5.2983</td>
      <td>2.8217</td>
    </tr>
    <tr>
      <th>37</th>
      <td>Roach</td>
      <td>SA</td>
      <td>78.0</td>
      <td>17.5</td>
      <td>18.8</td>
      <td>21.2</td>
      <td>5.5756</td>
      <td>2.9044</td>
    </tr>
  </tbody>
</table>
</div>

In [80]:
data.query("Species!='Bream' and Width>5").head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>54</th>
      <td>Roach</td>
      <td>EN</td>
      <td>390.0</td>
      <td>29.5</td>
      <td>31.7</td>
      <td>35.0</td>
      <td>9.4850</td>
      <td>5.3550</td>
    </tr>
    <tr>
      <th>58</th>
      <td>Whitefish</td>
      <td>EN</td>
      <td>540.0</td>
      <td>28.5</td>
      <td>31.0</td>
      <td>34.0</td>
      <td>10.7440</td>
      <td>6.5620</td>
    </tr>
    <tr>
      <th>59</th>
      <td>Whitefish</td>
      <td>EN</td>
      <td>800.0</td>
      <td>33.7</td>
      <td>36.4</td>
      <td>39.6</td>
      <td>11.7612</td>
      <td>6.5736</td>
    </tr>
  </tbody>
</table>
</div>

In [81]:
data.query("Species!='Bream' or Width>5").head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>Area</th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4</th>
      <td>Bream</td>
      <td>AF</td>
      <td>430.0</td>
      <td>26.5</td>
      <td>29.0</td>
      <td>34.0</td>
      <td>12.4440</td>
      <td>5.1340</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Bream</td>
      <td>SA</td>
      <td>500.0</td>
      <td>26.8</td>
      <td>29.7</td>
      <td>34.5</td>
      <td>14.1795</td>
      <td>5.2785</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Bream</td>
      <td>AN</td>
      <td>475.0</td>
      <td>28.4</td>
      <td>31.0</td>
      <td>36.2</td>
      <td>14.2628</td>
      <td>5.1042</td>
    </tr>
  </tbody>
</table>
</div>

##2. Aggregating 方法  
聚合： 针对有一个数值类型的列进行 包括 **sum**, **mean**, **median**,**max**,**min**等

In [82]:
# # 求Weight列到Width列的每一列的平均值
data_num = data.loc[:, 'Weight':'Width']
data_num.mean()
# data_num.median()
# data_num.sum()
# data_num.max()
# data_num.min()

Weight     398.326415
Length1     26.247170
Length2     28.415723
Length3     31.227044
Height       8.970994
Width        4.417486
dtype: float64

In [83]:
# #对某一列进行聚合
data.loc[:, 'Weight'].sum()
# data.loc[:,'Weight'].sum(axis=0)

63333.9

In [84]:
# 按行进行聚合
data_num.sum(axis=1)

0       336.1400
1       388.2856
2       438.5739
3       468.9855
4       537.0780
5       559.7298
6       610.4580
7       499.9600
8       561.5487
9       614.5860
10      589.9670
11      615.0860
12      615.1272
13      457.7857
14      718.7252
15      719.6180
16      821.8458
17      822.0355
18      733.7668
19      773.4014
20      700.4980
21      810.9640
22      746.5028
23      808.9992
24      829.2295
25      855.1132
26      850.0518
27      846.5685
28      983.4880
29     1138.6600
         ...
129     413.3658
130     416.8208
131     422.2082
132     555.8665
133     470.8730
134     595.6025
135     649.2840
136     681.8156
137     646.8560
138     717.5620
139     927.0560
140    1120.1974
141    1435.3712
142    1795.7440
143    1745.7440
144    1858.6920
145      39.3864
146      42.7320
147      42.1768
148      46.6760
149      47.4604
150      46.6634
151      49.6977
152      49.4798
153      49.7528
154      52.7840
155      54.6990
156      54.6328
157      67.3400
158      69.7114
Length: 159, dtype: float64

##3. 非Aggregating方法
round(n): 取小数点后n位

In [85]:
data_num.round(2).head(3)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Weight</th>
      <th>Length1</th>
      <th>Length2</th>
      <th>Length3</th>
      <th>Height</th>
      <th>Width</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>242.0</td>
      <td>23.2</td>
      <td>25.4</td>
      <td>30.0</td>
      <td>11.52</td>
      <td>4.02</td>
    </tr>
    <tr>
      <th>1</th>
      <td>290.0</td>
      <td>24.0</td>
      <td>26.3</td>
      <td>31.2</td>
      <td>12.48</td>
      <td>4.31</td>
    </tr>
    <tr>
      <th>2</th>
      <td>340.0</td>
      <td>23.9</td>
      <td>26.5</td>
      <td>31.1</td>
      <td>12.38</td>
      <td>4.70</td>
    </tr>
  </tbody>
</table>
</div>

##4. Aggregating with groups
####4.1 统计某一列每一个取值的频次

In [86]:
# #统计Species中每个类型的个数
data['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

####4.2 单列聚合，单个聚合函数

In [87]:
# #统计每种species的Height的平均值
data.groupby("Species")["Height"].agg([("height_mean", "mean")])
# #or
# data.groupby("Species").agg({"Height": [("height_mean", "mean")]})

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>height_mean</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Bream</th>
      <td>15.183211</td>
    </tr>
    <tr>
      <th>Parkki</th>
      <td>8.962427</td>
    </tr>
    <tr>
      <th>Perch</th>
      <td>7.861870</td>
    </tr>
    <tr>
      <th>Pike</th>
      <td>7.713771</td>
    </tr>
    <tr>
      <th>Roach</th>
      <td>6.694795</td>
    </tr>
    <tr>
      <th>Smelt</th>
      <td>2.209371</td>
    </tr>
    <tr>
      <th>Whitefish</th>
      <td>10.027167</td>
    </tr>
  </tbody>
</table>
</div>

####4.3 单列聚合，多个聚合函数

In [88]:
# # 统计每种species的Height的平均值，最大值，总数
# # or
# data.groupby("Species")["Height"].agg([("height_mean", "mean"), 
#                                        ("height_max", "max"), 
#                                        ("height_count", "count")])
data.groupby('Species').agg({"Height": [("height_mean", "mean"), 
                                        ("height_max", "max"), 
                                        ("height_count", "count")]})

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }

    .dataframe thead tr:last-of-type th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="3" halign="left">Height</th>
    </tr>
    <tr>
      <th></th>
      <th>height_mean</th>
      <th>height_max</th>
      <th>height_count</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Bream</th>
      <td>15.183211</td>
      <td>18.9570</td>
      <td>35</td>
    </tr>
    <tr>
      <th>Parkki</th>
      <td>8.962427</td>
      <td>11.3680</td>
      <td>11</td>
    </tr>
    <tr>
      <th>Perch</th>
      <td>7.861870</td>
      <td>12.8002</td>
      <td>56</td>
    </tr>
    <tr>
      <th>Pike</th>
      <td>7.713771</td>
      <td>10.8120</td>
      <td>17</td>
    </tr>
    <tr>
      <th>Roach</th>
      <td>6.694795</td>
      <td>9.4850</td>
      <td>20</td>
    </tr>
    <tr>
      <th>Smelt</th>
      <td>2.209371</td>
      <td>2.9322</td>
      <td>14</td>
    </tr>
    <tr>
      <th>Whitefish</th>
      <td>10.027167</td>
      <td>12.3540</td>
      <td>6</td>
    </tr>
  </tbody>
</table>
</div>

####4.4 按多个列进行聚合

In [89]:
data.groupby(['Species','Area']).agg({"Height": [("height_mean", "mean"), 
                                        ("height_max", "max"), 
                                        ("height_count", "count")]})

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }

    .dataframe thead tr:last-of-type th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan="3" halign="left">Height</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th>height_mean</th>
      <th>height_max</th>
      <th>height_count</th>
    </tr>
    <tr>
      <th>Species</th>
      <th>Area</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="9" valign="top">Bream</th>
      <th>AD</th>
      <td>16.240500</td>
      <td>16.2405</td>
      <td>1</td>
    </tr>
    <tr>
      <th>AF</th>
      <td>15.000078</td>
      <td>18.6354</td>
      <td>9</td>
    </tr>
    <tr>
      <th>AM</th>
      <td>15.559360</td>
      <td>17.6235</td>
      <td>5</td>
    </tr>
    <tr>
      <th>AN</th>
      <td>14.262800</td>
      <td>14.2628</td>
      <td>1</td>
    </tr>
    <tr>
      <th>AS</th>
      <td>14.117050</td>
      <td>16.3618</td>
      <td>6</td>
    </tr>
    <tr>
      <th>CH</th>
      <td>17.611900</td>
      <td>18.9570</td>
      <td>4</td>
    </tr>
    <tr>
      <th>EN</th>
      <td>18.395550</td>
      <td>18.7542</td>
      <td>2</td>
    </tr>
    <tr>
      <th>NY</th>
      <td>13.615640</td>
      <td>14.9544</td>
      <td>5</td>
    </tr>
    <tr>
      <th>SA</th>
      <td>14.046200</td>
      <td>14.1795</td>
      <td>2</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Parkki</th>
      <th>AD</th>
      <td>7.622980</td>
      <td>8.8928</td>
      <td>5</td>
    </tr>
    <tr>
      <th>CH</th>
      <td>10.078633</td>
      <td>11.3680</td>
      <td>6</td>
    </tr>
    <tr>
      <th rowspan="7" valign="top">Perch</th>
      <th>AD</th>
      <td>5.869533</td>
      <td>6.7920</td>
      <td>6</td>
    </tr>
    <tr>
      <th>AK</th>
      <td>5.740190</td>
      <td>6.3840</td>
      <td>10</td>
    </tr>
    <tr>
      <th>AM</th>
      <td>12.488800</td>
      <td>12.4888</td>
      <td>1</td>
    </tr>
    <tr>
      <th>AS</th>
      <td>4.152286</td>
      <td>5.2224</td>
      <td>7</td>
    </tr>
    <tr>
      <th>EN</th>
      <td>9.782120</td>
      <td>12.4313</td>
      <td>15</td>
    </tr>
    <tr>
      <th>NY</th>
      <td>6.926122</td>
      <td>8.3230</td>
      <td>9</td>
    </tr>
    <tr>
      <th>SA</th>
      <td>12.127987</td>
      <td>12.8002</td>
      <td>8</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Pike</th>
      <th>AK</th>
      <td>8.871389</td>
      <td>10.8120</td>
      <td>9</td>
    </tr>
    <tr>
      <th>AM</th>
      <td>6.411450</td>
      <td>7.2900</td>
      <td>8</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">Roach</th>
      <th>AD</th>
      <td>6.114600</td>
      <td>6.1146</td>
      <td>1</td>
    </tr>
    <tr>
      <th>AF</th>
      <td>6.998000</td>
      <td>8.8768</td>
      <td>4</td>
    </tr>
    <tr>
      <th>AK</th>
      <td>7.084150</td>
      <td>7.5344</td>
      <td>2</td>
    </tr>
    <tr>
      <th>AS</th>
      <td>6.171550</td>
      <td>7.0334</td>
      <td>4</td>
    </tr>
    <tr>
      <th>CH</th>
      <td>7.396800</td>
      <td>7.3968</td>
      <td>1</td>
    </tr>
    <tr>
      <th>EN</th>
      <td>7.086100</td>
      <td>9.4850</td>
      <td>5</td>
    </tr>
    <tr>
      <th>NY</th>
      <td>6.265950</td>
      <td>6.9153</td>
      <td>2</td>
    </tr>
    <tr>
      <th>SA</th>
      <td>5.575600</td>
      <td>5.5756</td>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Smelt</th>
      <th>NY</th>
      <td>2.467800</td>
      <td>2.9322</td>
      <td>6</td>
    </tr>
    <tr>
      <th>SA</th>
      <td>2.015550</td>
      <td>2.2139</td>
      <td>8</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Whitefish</th>
      <th>AD</th>
      <td>12.354000</td>
      <td>12.3540</td>
      <td>1</td>
    </tr>
    <tr>
      <th>EN</th>
      <td>9.561800</td>
      <td>11.7612</td>
      <td>5</td>
    </tr>
  </tbody>
</table>
</div>

####4.5 构建透视表

In [98]:
pt = data.pivot_table(index="Species",columns="Area",values="Height",aggfunc="mean")
pt

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Area</th>
      <th>AD</th>
      <th>AF</th>
      <th>AK</th>
      <th>AM</th>
      <th>AN</th>
      <th>AS</th>
      <th>CH</th>
      <th>EN</th>
      <th>NY</th>
      <th>SA</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Bream</th>
      <td>16.240500</td>
      <td>15.000078</td>
      <td>NaN</td>
      <td>15.55936</td>
      <td>14.2628</td>
      <td>14.117050</td>
      <td>17.611900</td>
      <td>18.39555</td>
      <td>13.615640</td>
      <td>14.046200</td>
    </tr>
    <tr>
      <th>Parkki</th>
      <td>7.622980</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>10.078633</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Perch</th>
      <td>5.869533</td>
      <td>NaN</td>
      <td>5.740190</td>
      <td>12.48880</td>
      <td>NaN</td>
      <td>4.152286</td>
      <td>NaN</td>
      <td>9.78212</td>
      <td>6.926122</td>
      <td>12.127987</td>
    </tr>
    <tr>
      <th>Pike</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>8.871389</td>
      <td>6.41145</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Roach</th>
      <td>6.114600</td>
      <td>6.998000</td>
      <td>7.084150</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>6.171550</td>
      <td>7.396800</td>
      <td>7.08610</td>
      <td>6.265950</td>
      <td>5.575600</td>
    </tr>
    <tr>
      <th>Smelt</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2.467800</td>
      <td>2.015550</td>
    </tr>
    <tr>
      <th>Whitefish</th>
      <td>12.354000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>9.56180</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

##5. styling Dataframe

In [104]:
s = data_num.style.highlight_max()
# #s是HTML输出，不能直接在pycharm控制台显示，需要在jupyter中显示
s.render()

'<style  type="text/css" >\n    #T_6d8b192a_a712_11ea_9674_049226bdf81crow29_col4 {\n            background-color:  yellow;\n        }    #T_6d8b192a_a712_11ea_9674_049226bdf81crow126_col5 {\n            background-color:  yellow;\n        }    #T_6d8b192a_a712_11ea_9674_049226bdf81crow144_col0 {\n            background-color:  yellow;\n        }    #T_6d8b192a_a712_11ea_9674_049226bdf81crow144_col1 {\n            background-color:  yellow;\n        }    #T_6d8b192a_a712_11ea_9674_049226bdf81crow144_col2 {\n            background-color:  yellow;\n        }    #T_6d8b192a_a712_11ea_9674_049226bdf81crow144_col3 {\n            background-color:  yellow;\n        }</style><table id="T_6d8b192a_a712_11ea_9674_049226bdf81c" ><thead>    <tr>        <th class="blank level0" ></th>        <th class="col_heading level0 col0" >Weight</th>        <th class="col_heading level0 col1" >Length1</th>        <th class="col_heading level0 col2" >Length2</th>        <th class="col_heading level0 col3" >Length3</th>        <th class="col_heading level0 col4" >Height</th>        <th class="col_heading level0 col5" >Width</th>    </tr></thead><tbody>\n                <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row0" class="row_heading level0 row0" >0</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow0_col0" class="data row0 col0" >242</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow0_col1" class="data row0 col1" >23.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow0_col2" class="data row0 col2" >25.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow0_col3" class="data row0 col3" >30</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow0_col4" class="data row0 col4" >11.52</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow0_col5" class="data row0 col5" >4.02</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row1" class="row_heading level0 row1" >1</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow1_col0" class="data row1 col0" >290</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow1_col1" class="data row1 col1" >24</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow1_col2" class="data row1 col2" >26.3</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow1_col3" class="data row1 col3" >31.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow1_col4" class="data row1 col4" >12.48</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow1_col5" class="data row1 col5" >4.3056</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row2" class="row_heading level0 row2" >2</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow2_col0" class="data row2 col0" >340</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow2_col1" class="data row2 col1" >23.9</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow2_col2" class="data row2 col2" >26.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow2_col3" class="data row2 col3" >31.1</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow2_col4" class="data row2 col4" >12.3778</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow2_col5" class="data row2 col5" >4.6961</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row3" class="row_heading level0 row3" >3</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow3_col0" class="data row3 col0" >363</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow3_col1" class="data row3 col1" >26.3</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow3_col2" class="data row3 col2" >29</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow3_col3" class="data row3 col3" >33.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow3_col4" class="data row3 col4" >12.73</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow3_col5" class="data row3 col5" >4.4555</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row4" class="row_heading level0 row4" >4</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow4_col0" class="data row4 col0" >430</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow4_col1" class="data row4 col1" >26.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow4_col2" class="data row4 col2" >29</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow4_col3" class="data row4 col3" >34</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow4_col4" class="data row4 col4" >12.444</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow4_col5" class="data row4 col5" >5.134</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row5" class="row_heading level0 row5" >5</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow5_col0" class="data row5 col0" >450</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow5_col1" class="data row5 col1" >26.8</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow5_col2" class="data row5 col2" >29.7</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow5_col3" class="data row5 col3" >34.7</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow5_col4" class="data row5 col4" >13.6024</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow5_col5" class="data row5 col5" >4.9274</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row6" class="row_heading level0 row6" >6</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow6_col0" class="data row6 col0" >500</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow6_col1" class="data row6 col1" >26.8</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow6_col2" class="data row6 col2" >29.7</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow6_col3" class="data row6 col3" >34.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow6_col4" class="data row6 col4" >14.1795</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow6_col5" class="data row6 col5" >5.2785</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row7" class="row_heading level0 row7" >7</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow7_col0" class="data row7 col0" >390</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow7_col1" class="data row7 col1" >27.6</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow7_col2" class="data row7 col2" >30</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow7_col3" class="data row7 col3" >35</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow7_col4" class="data row7 col4" >12.67</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow7_col5" class="data row7 col5" >4.69</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row8" class="row_heading level0 row8" >8</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow8_col0" class="data row8 col0" >450</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow8_col1" class="data row8 col1" >27.6</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow8_col2" class="data row8 col2" >30</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow8_col3" class="data row8 col3" >35.1</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow8_col4" class="data row8 col4" >14.0049</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow8_col5" class="data row8 col5" >4.8438</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row9" class="row_heading level0 row9" >9</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow9_col0" class="data row9 col0" >500</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow9_col1" class="data row9 col1" >28.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow9_col2" class="data row9 col2" >30.7</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow9_col3" class="data row9 col3" >36.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow9_col4" class="data row9 col4" >14.2266</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow9_col5" class="data row9 col5" >4.9594</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row10" class="row_heading level0 row10" >10</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow10_col0" class="data row10 col0" >475</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow10_col1" class="data row10 col1" >28.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow10_col2" class="data row10 col2" >31</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow10_col3" class="data row10 col3" >36.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow10_col4" class="data row10 col4" >14.2628</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow10_col5" class="data row10 col5" >5.1042</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row11" class="row_heading level0 row11" >11</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow11_col0" class="data row11 col0" >500</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow11_col1" class="data row11 col1" >28.7</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow11_col2" class="data row11 col2" >31</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow11_col3" class="data row11 col3" >36.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow11_col4" class="data row11 col4" >14.3714</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow11_col5" class="data row11 col5" >4.8146</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row12" class="row_heading level0 row12" >12</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow12_col0" class="data row12 col0" >500</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow12_col1" class="data row12 col1" >29.1</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow12_col2" class="data row12 col2" >31.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow12_col3" class="data row12 col3" >36.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow12_col4" class="data row12 col4" >13.7592</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow12_col5" class="data row12 col5" >4.368</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row13" class="row_heading level0 row13" >13</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow13_col0" class="data row13 col0" >340</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow13_col1" class="data row13 col1" >29.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow13_col2" class="data row13 col2" >32</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow13_col3" class="data row13 col3" >37.3</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow13_col4" class="data row13 col4" >13.9129</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow13_col5" class="data row13 col5" >5.0728</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row14" class="row_heading level0 row14" >14</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow14_col0" class="data row14 col0" >600</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow14_col1" class="data row14 col1" >29.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow14_col2" class="data row14 col2" >32</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow14_col3" class="data row14 col3" >37.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow14_col4" class="data row14 col4" >14.9544</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow14_col5" class="data row14 col5" >5.1708</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row15" class="row_heading level0 row15" >15</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow15_col0" class="data row15 col0" >600</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow15_col1" class="data row15 col1" >29.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow15_col2" class="data row15 col2" >32</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow15_col3" class="data row15 col3" >37.2</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow15_col4" class="data row15 col4" >15.438</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow15_col5" class="data row15 col5" >5.58</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row16" class="row_heading level0 row16" >16</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow16_col0" class="data row16 col0" >700</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow16_col1" class="data row16 col1" >30.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow16_col2" class="data row16 col2" >33</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow16_col3" class="data row16 col3" >38.3</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow16_col4" class="data row16 col4" >14.8604</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow16_col5" class="data row16 col5" >5.2854</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row17" class="row_heading level0 row17" >17</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow17_col0" class="data row17 col0" >700</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow17_col1" class="data row17 col1" >30.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow17_col2" class="data row17 col2" >33</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow17_col3" class="data row17 col3" >38.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow17_col4" class="data row17 col4" >14.938</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow17_col5" class="data row17 col5" >5.1975</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row18" class="row_heading level0 row18" >18</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow18_col0" class="data row18 col0" >610</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow18_col1" class="data row18 col1" >30.9</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow18_col2" class="data row18 col2" >33.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow18_col3" class="data row18 col3" >38.6</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow18_col4" class="data row18 col4" >15.633</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow18_col5" class="data row18 col5" >5.1338</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row19" class="row_heading level0 row19" >19</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow19_col0" class="data row19 col0" >650</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow19_col1" class="data row19 col1" >31</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow19_col2" class="data row19 col2" >33.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow19_col3" class="data row19 col3" >38.7</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow19_col4" class="data row19 col4" >14.4738</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow19_col5" class="data row19 col5" >5.7276</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row20" class="row_heading level0 row20" >20</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow20_col0" class="data row20 col0" >575</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow20_col1" class="data row20 col1" >31.3</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow20_col2" class="data row20 col2" >34</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow20_col3" class="data row20 col3" >39.5</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow20_col4" class="data row20 col4" >15.1285</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow20_col5" class="data row20 col5" >5.5695</td>\n            </tr>\n            <tr>\n                        <th id="T_6d8b192a_a712_11ea_9674_049226bdf81clevel0_row21" class="row_heading level0 row21" >21</th>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow21_col0" class="data row21 col0" >685</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow21_col1" class="data row21 col1" >31.4</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow21_col2" class="data row21 col2" >34</td>\n                        <td id="T_6d8b192a_a712_11ea_9674_049226bdf81crow21_col3" class="data row21 col3" >39.2</td>\n                        <td id="T_6d8b192a_